

/**
 * ROS message: hako_srv_msgs/GetEventResponse
 * Generated by hakoniwa-ros2pdu.
 */
export class GetEventResponse {
/** @type { number } */
    event_code;


    constructor() {
        this.event_code = 0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'event_code'
            const field_val = this.event_code;
            if (typeof field_val?.toDict === 'function') {
                d['event_code'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['event_code'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['event_code'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { GetEventResponse }
     */
    static fromDict(d) {
        const obj = new GetEventResponse();
        if (d.hasOwnProperty('event_code')) {
            obj.event_code = d.event_code;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { GetEventResponse }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
