

/**
 * ROS message: hako_srv_msgs/GetSimStateResponse
 * Generated by hakoniwa-ros2pdu.
 */
export class GetSimStateResponse {
/** @type { number } */
    sim_state;


    constructor() {
        this.sim_state = 0;
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'sim_state'
            const field_val = this.sim_state;
            if (typeof field_val?.toDict === 'function') {
                d['sim_state'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['sim_state'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['sim_state'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { GetSimStateResponse }
     */
    static fromDict(d) {
        const obj = new GetSimStateResponse();
        if (d.hasOwnProperty('sim_state')) {
            obj.sim_state = d.sim_state;
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { GetSimStateResponse }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
