import { GetEventRequest } from '../hako_srv_msgs/pdu_jstype_GetEventRequest.js';
import { ServiceRequestHeader } from '../hako_srv_msgs/pdu_jstype_ServiceRequestHeader.js';


/**
 * ROS message: hako_srv_msgs/GetEventRequestPacket
 * Generated by hakoniwa-ros2pdu.
 */
export class GetEventRequestPacket {
/** @type { ServiceRequestHeader } */
    header;
/** @type { GetEventRequest } */
    body;


    constructor() {
        this.header = new ServiceRequestHeader();
        this.body = new GetEventRequest();
    }

    /**
     * @returns {object}
     */
    toDict() {
        const d = {};
        {
            // handle field 'header'
            const field_val = this.header;
            if (typeof field_val?.toDict === 'function') {
                d['header'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['header'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['header'] = field_val;
            }
        }
        {
            // handle field 'body'
            const field_val = this.body;
            if (typeof field_val?.toDict === 'function') {
                d['body'] = field_val.toDict();
            } else if (Array.isArray(field_val)) {
                d['body'] = field_val.map(item => typeof item?.toDict === 'function' ? item.toDict() : item);
            } else {
                d['body'] = field_val;
            }
        }
        return d;
    }

    /**
     * @param {object} d
     * @returns { GetEventRequestPacket }
     */
    static fromDict(d) {
        const obj = new GetEventRequestPacket();
        if (d.hasOwnProperty('header')) {
            const field_class = ServiceRequestHeader;
            if (d.header) {
                obj.header = field_class.fromDict(d.header);
            }
        }
        if (d.hasOwnProperty('body')) {
            const field_class = GetEventRequest;
            if (d.body) {
                obj.body = field_class.fromDict(d.body);
            }
        }
        return obj;
    }

    /**
     * @returns {string}
     */
    toJSON(indent = 2) {
        return JSON.stringify(this.toDict(), null, indent);
    }

    /**
     * @param {string} json_str
     * @returns { GetEventRequestPacket }
     */
    static fromJSON(json_str) {
        return this.fromDict(JSON.parse(json_str));
    }
}
