from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class AckEventRequest:
    """
    ROS message: hako_srv_msgs/AckEventRequest
    Generated by hakoniwa-ros2pdu.
    """

    name: str
    event_code: int

    def __init__(self):
        self.name = ""
        self.event_code = 0

    def __str__(self):
        return f"AckEventRequest(" + ", ".join([
            f"name={self.name}"
            f"event_code={self.event_code}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'name'
        field_val = self.name
        if isinstance(field_val, bytearray):
            d['name'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['name'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['name'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['name'] = field_val
        # handle field 'event_code'
        field_val = self.event_code
        if isinstance(field_val, bytearray):
            d['event_code'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['event_code'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['event_code'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['event_code'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'name'
        if 'name' in d:
            field_type = cls.__annotations__.get('name')
            value = d['name']
            
            if field_type is bytearray:
                obj.name = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.name = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.name = value
            elif hasattr(field_type, 'from_dict'):
                obj.name = field_type.from_dict(value)
            else:
                obj.name = value
        # handle field 'event_code'
        if 'event_code' in d:
            field_type = cls.__annotations__.get('event_code')
            value = d['event_code']
            
            if field_type is bytearray:
                obj.event_code = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.event_code = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.event_code = value
            elif hasattr(field_type, 'from_dict'):
                obj.event_code = field_type.from_dict(value)
            else:
                obj.event_code = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
