from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class AckEventResponse:
    """
    ROS message: hako_srv_msgs/AckEventResponse
    Generated by hakoniwa-ros2pdu.
    """

    ack_code: int

    def __init__(self):
        self.ack_code = 0

    def __str__(self):
        return f"AckEventResponse(" + ", ".join([
            f"ack_code={self.ack_code}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'ack_code'
        field_val = self.ack_code
        if isinstance(field_val, bytearray):
            d['ack_code'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['ack_code'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['ack_code'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['ack_code'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'ack_code'
        if 'ack_code' in d:
            field_type = cls.__annotations__.get('ack_code')
            value = d['ack_code']
            
            if field_type is bytearray:
                obj.ack_code = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.ack_code = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.ack_code = value
            elif hasattr(field_type, 'from_dict'):
                obj.ack_code = field_type.from_dict(value)
            else:
                obj.ack_code = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
