from typing import List

# dependencies for the generated Python class


# class definition for the ROS message
class GetSimStateResponse:
    """
    ROS message: hako_srv_msgs/GetSimStateResponse
    Generated by hakoniwa-ros2pdu.
    """

    sim_state: int

    def __init__(self):
        self.sim_state = 0

    def __str__(self):
        return f"GetSimStateResponse(" + ", ".join([
            f"sim_state={self.sim_state}"
        ]) + ")"

    def __repr__(self):
        return self.__str__()

    def to_dict(self):
        """
        Convert the object to a dictionary.
        """
        d = {}
        # handle field 'sim_state'
        field_val = self.sim_state
        if isinstance(field_val, bytearray):
            d['sim_state'] = list(field_val)
        elif hasattr(field_val, 'to_dict'):
            d['sim_state'] = field_val.to_dict()
        elif isinstance(field_val, list):
            d['sim_state'] = [item.to_dict() if hasattr(item, 'to_dict') else item for item in field_val]
        else:
            d['sim_state'] = field_val
        return d

    @classmethod
    def from_dict(cls, d: dict):
        """
        Create an object from a dictionary.
        """
        obj = cls()
        # handle field 'sim_state'
        if 'sim_state' in d:
            field_type = cls.__annotations__.get('sim_state')
            value = d['sim_state']
            
            if field_type is bytearray:
                obj.sim_state = bytearray(value)
            elif hasattr(field_type, '__origin__') and field_type.__origin__ is list:
                list_item_type = field_type.__args__[0]
                if hasattr(list_item_type, 'from_dict'):
                    obj.sim_state = [list_item_type.from_dict(item) for item in value]
                else:
                    obj.sim_state = value
            elif hasattr(field_type, 'from_dict'):
                obj.sim_state = field_type.from_dict(value)
            else:
                obj.sim_state = value
        return obj

    def to_json(self, indent=2):
        """
        Convert the object to a JSON string.
        """
        import json
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_json(cls, json_str: str):
        """
        Create an object from a JSON string.
        """
        import json
        return cls.from_dict(json.loads(json_str))
